[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Craig 'Craole' Cole <craole@tuta.io>"]
license = "MIT OR Apache-2.0"
description = "Various utilities for development."
homepage = "https://craole.cc/utils"
repository = "https://github.com/craole-cc/ccutils"

[workspace]
members = [
  #| Support
  # "configuration",
  "crates/erks",
  "crates/logline",
  "crates/intime",

  #| Core
  "crates/embellish",
  "crates/grit",
  "crates/slink",
  "crates/sysfo",
  "crates/whers",
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = { level = "forbid", priority = -1 }
unused = "allow"

[workspace.dependencies]
#| Handlers
thiserror = "1.0.49"
anyhow = "1.0.89"
once_cell = "1.20.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

#| Information
sysinfo = "0.32.0"
battery = "0.7.8"
chrono = "0.4.23"
iana-time-zone = "0.1.61"

#| Utilities
crossterm = "0.28.1"
clap = { version = "4.5.20", features = ["derive", "cargo"] }
directories = "5.0.1"
current_dir = "0.1.1"
glob = "0.3.1"
tempfile = "3.13.0"
regex = "1"
ignore = "0.4"
num_cpus = "1.0"
strsim = "0.11.1"
which = "6.0.3"

#| Types
uom = "0.36.0"

#| Development
criterion = "0.5.1"
