[package]
name = "whers"
description = "Search for files matching a pattern"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
logline = { path = "../logline" }
clap = { workspace = true }

rust_search = { workspace = true }
rust_search_fork = { workspace = true }

regex = { workspace = true }
ignore = { workspace = true }
num_cpus = { workspace = true }
dirs = { workspace = true }
strsim = { workspace = true }

# tracing = { workspace = true }
# tracing-subscriber = { workspace = true }
which = { workspace = true }
