[package]
name = "decimal-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.32"
bigdecimal = { version = "0.4", optional = true }
mimalloc = { version = "0.1", optional = true }
lru = "0.14.0"
dashmap = "6.1.0"
simd-json = "0.15.1"
thiserror = "2.0.12"
cfg-if = "1.0"

[features]
default = ["std-alloc"]
big-decimal = ["dep:bigdecimal"]
std-alloc = []
mi-alloc = ["dep:mimalloc"]
simd = []

[dev-dependencies]
criterion = "0.6.0"
proptest = "1.3"
test-case = "3.3"

[[bench]]
name = "parse_bench"
harness = false
