# Cargo config file.
# https://doc.rust-lang.org/cargo/reference/config.html

#| Aliases
[alias]
br = "build --release"
rr = "run --release"
rq = "run --quiet"
rp = "run --package"
rrp = "run  --release --package"
rqp = "run --quiet --package"
wq = "watch --quiet --clear --exec"
wrp = "wq rrp --"
wqp = "watch --quiet --clear --exec rqp"

#> dots
rr-dots = "rrp dots"
rq-dots = "rqp dots"
wr-dots = "wq rr-dots"
wq-dots = "wq rq-dots"

#> app
rr-app = "rrp app"
rq-app = "rqp app"
wr-app = "wq rr-app"
wq-app = "wq rq-app"

#> colorscheme
rr-colorscheme = "rrp colorscheme"
rq-colorscheme = "rqp colorscheme"
wr-colorscheme = "wq rr-colorscheme"
wq-colorscheme = "wq rq-colorscheme"

#> genna
rr-genna = "rrp genna"
rq-genna = "rqp genna"
wr-genna = "wq rr-genna"
wq-genna = "wq rq-genna"

#> numba
rr-numba = "rrp numba"
rq-numba = "rqp numba"
wr-numba = "wq rr-numba"
wq-numba = "wq rq-numba"

#> scraps
rr-scraps = "rrp scraps"
rq-scraps = "rqp scraps"
wr-scraps = "wq rr-scraps"
wq-scraps = "wq rq-scraps"

#> sysfo
rr-sysfo = "rrp sysfo"
rq-sysfo = "rqp sysfo"
wr-sysfo = "wq rr-sysfo"
wq-sysfo = "wq rq-sysfo"

#> intime
rr-intime = "rrp intime"
rq-intime = "rqp intime"
wr-intime = "wrp rrp intime"
w-intime = "wq rq-intime"

#> wallter
rr-wallter = "rrp wallter"
rq-wallter = "rqp wallter"
wr-wallter = "wq rr-wallter"
wq-wallter = "wq rq-wallter"

#> whers
rr-whers = "rrp whers"
rq-whers = "rqp whers"
wr-whers = "wq rr-whers"
wq-whers = "wq rq-whers"

#| Terminal Config
[term]
quiet = false

#| Environment Variables
[env]
# BROWSER = "firefox"
RUST_LOG = "erks=trace,logline=trace,intime=trace,numba=trace,app=trace,ccutils=info,dots=trace,colorscheme=trace,embellish=trace,genna=trace,grit=trace,scraps=trace,slink=trace,sysfo=trace,wallter=trace,whers=trace"
