[package]
name = "slink"
version = "0.1.0"
description = "A utility for managing symbolic links agnostic of the OS."
edition = { workspace = true }

[dependencies]
chrono = { workspace = true }             # We shouldn't need this, we can use sysfo
clap = { workspace = true }
directories = { workspace = true }
glob = { workspace = true }
thiserror = { workspace = true }          # TODO: Replace with erks
tracing = { workspace = true }            # TODO: Replace with logline
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
