#!/bin/sh

# Helper function to set aliases
set_alias() {
  if [ "$FISH_VERSION" ]; then
    alias "$1" "$2"
  elif [ "$ZSH_VERSION" ]; then
    alias "$1"="$2"
  elif [ "$KSH_VERSION" ]; then
    alias "$1"="$2"
  fi
}

#@ Aliases @#
app_available bat && set_alias cat 'bat --style=plain'

app_available cargo && set_alias A 'cargo add'
app_available cargo && set_alias B 'cargo build --release'
app_available cargo && set_alias C 'project_clean'
app_available dust && set_alias D 'cargo remove'
app_available hx && set_alias E 'project_edit'
set_alias F 'project_format'
app_available cargo && set_alias G 'cargo generate'
app_available hx && set_alias H 'project_edit "$PRJ_ROOT"'
set_alias I 'project_init'
app_available just && set_alias J 'just'
set_alias K 'exit'

if app_available eza; then
  set_alias ls 'eza --almost-all --group-directories-first --color=always --icons=always --git --git-ignore --time-style relative --total-size --smart-group'
  set_alias L 'ls --long '
  set_alias La 'ls --long --git'
  set_alias Lt 'L --tree'
elif app_available lsd; then
  set_alias ls 'lsd --almost-all --group-directories-first --color=always'
  set_alias L 'ls --long --git --date=relative --versionsort --total-size'
  set_alias Lt 'L --tree'
else
  set_alias ls 'ls --almost-all --group-directories-first --color=always'
  set_alias L 'ls -l'
  set_alias Lt 'L --recursive'
fi

app_available pls && set_alias Lp 'pls --det perm --det oct --det user --det group --det mtime --det git --det size --header false'
set_alias M 'mkdir --parents'
app_available cargo && set_alias N 'cargo new'
app_available cargo && set_alias O ''
set_alias P 'project_info'
set_alias Ps 'project_info --size'
app_available cargo && set_alias Q 'cargo watch --quiet --clear --exec "run --quiet --"'
app_available cargo && set_alias R 'cargo run --release'
app_available cargo && set_alias S 'cargo search'
set_alias T 'create_file'
set_alias U 'project_update'

app_available code && set_alias V "code \"$PRJ_ROOT\""
app_available cargo && set_alias W 'cargo watch --quiet --clear --exec "run --"'
app_available cargo && set_alias X 'project_clean --reset'

if [ -f "$PRJ_INFO" ]; then
  set_alias Y "cat \"$PRJ_INFO\""
else
  set_alias Y 'project_info'
fi

set_alias Z 'tokei'

print_heading "Aliases"
print_block "$(alias | grep "alias [A-Z]=")"
