#!/bin/sh

pout --heading "Utilities"

apps="cargo code dust hx just rustc tokei treefmt"
# shellcheck disable=SC2086
set -- $apps

while [ "$#" -gt 0 ]; do
	if app_available "$1"; then
		pout --status --success --app "$1"
	else
		pout --status --failure --app "$1"
	fi
	shift
done
