#!/bin/sh

main() {
  parse_arguments "$@"
  execute "$args"
}

execute() {
  if [ "$block" ]; then
    print_block "$1"
  elif [ "$heading" ]; then
    print_heading "$1"
  elif [ "$status" ]; then
    return
  else
    printf "%s" "$1"
  fi
}

parse_arguments() {
  unset block heading args
  while [ "$#" -gt 0 ]; do
    case "$1" in
    --block) block=true ;;
    --heading) heading=true ;;
    --status)
      status=true
      [ "$2" ] && shift && print_status "$@" && break
      ;;
    -*) ;;
    *) args="$args $1" ;;
    esac
    shift
  done
}
print_block() {
  printf "%s\n\n" "$*"
}

print_heading() {
  tput setaf 4
  printf "|> %s <|\n" "$*"
  tput sgr0
}

print_status() {
  unset app icon dep err
  while [ "$#" -gt 0 ]; do
    case "$1" in
    --success) icon="🟢" ;;
    --failure) icon="🔴" ;;
    --app) [ "$2" ] && app="$2" ;;
    --dependency) [ "$2" ] && dep="$2" ;;
    --error) [ "$2" ] && err="$2" ;;
    esac
    shift
  done

  [ "$app" ] && printf "%s %s\n" "$icon" "$app"
  [ "$dep" ] && {
    tput setaf 1
    printf "Missing dependency: " >&2
    tput sgr0
    printf "%s\n" "$dep" >&2
  }
  [ "$err" ] && {
    tput setaf 1
    printf "Error: %s\n" "$err" >&2
    tput sgr0
  }
}

main "$@"
