#!/bin/sh

case "$1" in
--block)
	[ "$2" ] && {
		shift
		printf "%s\n\n" "$*"
	}
	;;
--heading)
	[ "$2" ] && {
		tput setaf 4
		printf "|> %s <|\n" "$*"
		tput sgr0
	}
	;;
*) printf "%s" "$*" ;;
esac
