#!/bin/sh

eval "alias $1=$2"
# alias_name="$1"
# alias_command="$2"

# alias_name=
# alias_command="$2"

# if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
#   alias "$alias_name"="$alias_command"
# elif [ -n "$FISH_VERSION" ]; then
#   eval "alias $alias_name $alias_command"
# elif [ -n "$PSVersionTable" ]; then
#   New-Alias -Name "$alias_name" -Value "$alias_command" -Force -Scope Global
# else
#   echo "Unsupported shell"
#   return 1
# fi

# echo "Alias '$alias_name' set to '$alias_command'"
