[toolchain]
channel = "stable"

components = [
  # https://rust-lang.github.io/rustup/concepts/components.html
  "rustc",
  "cargo",
  "rustfmt",
  "rust-src",
  "rust-analyzer",
  "clippy",
  # "miri",
]
# # profile = "minimal"
# targets = [
#   "wasm32-unknown-unknown",
#   # "x86_64-unknown-linux-musl",
#   # "x86_64-unknown-linux-gnu",
#   # "aarch64-unknown-linux-musl",
# ]
